### ISSUE TITLE
Curious: What are you using this node for?

### ISSUE THREAD

**Issue by lgrkvst** [zinen/node-red-contrib-nordpool-api-plus#19]
Hi,

A mere question driven by interest as I would be very interested in hearing about the use-cases. What are you using this node for?

**Comment by zinen** [comment]
I use this mostly for displaying prices on a GUI at home to help guide when to start my power-hungry appliances. I also add tariffs to this GUI.

Was working on a notification system to tell me when the next day I should start the dishwasher. But due to current tariff model in year 2023 nearly only the tariffs have any effect my decision and these are static meaning I know every day when to start my appliances.
